### ISSUE TITLE
iceman-fx / be_tools:: Aufklappzeit änderbar? 

### ISSUE THREAD

**Issue by Koala** [Koala/ListeZumAbarbeitenWennZeitIst#2]
https://github.com/iceman-fx/be_tools/issues/34

Seitenmenü per JS auf-/zuklappen lassen. Code raussuchen / einfügen ... derzeit funktioniert es per CSS für mich ganz gut ...

**Comment by Koala** [comment]
addons/be_tools/assets/style.css

https://github.com/iceman-fx/be_tools/blob/1c73c24859da4bda9ac2cfe0e6c7e4efbf7156f8/assets/style.css#L52

Hier den Code anpassen:

```css
/*	nav.rex-nav-main, div.rex-nav-main, 
		.rex-nav-main-title, 
		.rex-nav-main-list>li>a, 
		.rex-nav-main-list>li.rex-has-icon>a>.rex-icon, 
		.rex-nav-main-list .cke5-icon-logo, 
		.rex-nav-main-list .watson-icon-logo 
		{ -webkit-transition: all 0.25s ease; transition: all 0.25s ease; }
*/		

    nav.rex-nav-main, div.rex-nav-main, 
		.rex-nav-main-list>li>a, 
		.rex-nav-main-list>li.rex-has-icon>a>.rex-icon, 
		.rex-nav-main-list .cke5-icon-logo, 
		.rex-nav-main-list .watson-icon-logo 
		{ -webkit-transition: all 0,25s ease; transition: all 0,25s ease; }


	nav.rex-nav-main, div.rex-nav-main, 
		.rex-nav-main-title
		{ 
            transition-delay: 1000ms;
            -webkit-transition: all 0,25s ease; 
            transition: all 0,25s ease; 
            
        }

```

Damit springt das Menü nicht gleich auf, wenn es mal kurz von der Maus gestreift wird.
